[package]
name = "nojson"
version = "0.3.7"
edition = "2024"
rust-version = "1.88"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
license = "MIT"
description = "A flexible JSON library with no dependencies and no macros"
homepage = "https://github.com/sile/nojson"
repository = "https://github.com/sile/nojson"
readme = "README.md"
categories = ["encoding", "parser-implementations"]

[workspace]
members = ["fuzz", "pbt"]
